# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, circuit_id=None, days_period=None, execution_time=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param circuit_id: The circuit_id of this InlineResponse200.  # noqa: E501
        :type circuit_id: str
        :param days_period: The days_period of this InlineResponse200.  # noqa: E501
        :type days_period: float
        :param execution_time: The execution_time of this InlineResponse200.  # noqa: E501
        :type execution_time: int
        """
        self.openapi_types = {
            'circuit_id': str,
            'days_period': float,
            'execution_time': int
        }

        self.attribute_map = {
            'circuit_id': 'circuitId',
            'days_period': 'daysPeriod',
            'execution_time': 'executionTime'
        }

        self._circuit_id = circuit_id
        self._days_period = days_period
        self._execution_time = execution_time

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def circuit_id(self):
        """Gets the circuit_id of this InlineResponse200.


        :return: The circuit_id of this InlineResponse200.
        :rtype: str
        """
        return self._circuit_id

    @circuit_id.setter
    def circuit_id(self, circuit_id):
        """Sets the circuit_id of this InlineResponse200.


        :param circuit_id: The circuit_id of this InlineResponse200.
        :type circuit_id: str
        """

        self._circuit_id = circuit_id

    @property
    def days_period(self):
        """Gets the days_period of this InlineResponse200.


        :return: The days_period of this InlineResponse200.
        :rtype: float
        """
        return self._days_period

    @days_period.setter
    def days_period(self, days_period):
        """Sets the days_period of this InlineResponse200.


        :param days_period: The days_period of this InlineResponse200.
        :type days_period: float
        """

        self._days_period = days_period

    @property
    def execution_time(self):
        """Gets the execution_time of this InlineResponse200.


        :return: The execution_time of this InlineResponse200.
        :rtype: int
        """
        return self._execution_time

    @execution_time.setter
    def execution_time(self, execution_time):
        """Sets the execution_time of this InlineResponse200.


        :param execution_time: The execution_time of this InlineResponse200.
        :type execution_time: int
        """

        self._execution_time = execution_time
