openapi: 3.0.0
info:
  contact:
    email: vlad.tudor@sapio.ro
  description: Application for running GPIO tasks.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Gardnero
  version: 1.0.0
servers:
  - url: /
paths:
  /configureCircuit:
    post:
      operationId: config_circuit
      description: Configure the time period
      parameters:
        - description: Circuit ID.
          explode: false
          in: query
          name: circuitId
          required: true
          schema:
            type: string
        - description: Number of days between execution.
          explode: false
          in: query
          name: daysPeriod
          required: true
          schema:
            type: number
        - description: Duration for the Circuit execution in seconds.
          explode: false
          in: query
          name: executionTime
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Response.
          content:
            application/yaml:
              schema:
                type: string
        '400':
          description: Invalid operation
      x-openapi-router-controller: controller
  /startCircuit:
    post:
      operationId: start_circuit
      description: Trigger the execution of a Circuit
      parameters:
        - description: Circuit ID.
          explode: false
          in: query
          name: circuitlId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response.
          content:
            application/yaml:
              schema:
                type: string
        '400':
          description: Invalid operation
      x-openapi-router-controller: controller
  /circuits:
    get:
      operationId: get_circuits
      description: Retrieve the current Circuits configuration [CircuitId, DaysPeriod, ExecutionTime].
      responses:
        '200':
          description: Response.
          content:
            application/yaml:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    circuitId:
                      type: string
                    daysPeriod:
                      type: number
                    executionTime:
                      type: integer
        '400':
          description: Invalid operation
      x-openapi-router-controller: controller

# components:
#   schemas:

